;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;				;
;	    VARIABLES		;
;				;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
ENUM $0000			;
				;
temp_1		DSB 1		;
temp_2		DSB 1		;
temp_3		DSB 1		;
temp_4		DSB 1		;
temp_5		DSB 1		;
temp_6		DSB 1		;
temp_7		DSB 1		;
temp_8		DSB 1		;
pointer_5	= temp_1	;
pointer_6	= temp_3	;
pointer_7	= temp_5	;
pointer_8	= temp_7	;
				;
pointer_1	DSB 2		;
pointer_2	DSB 2		;
pointer_3	DSB 2		;
pointer_4	DSB 2		;
temp_9		= pointer_1	;
temp_10		= pointer_1+1	;
temp_11		= pointer_2	;
temp_12		= pointer_2+1	;
temp_13		= pointer_3	;
temp_14		= pointer_3+1	;
temp_15		= pointer_4	;
temp_16		= pointer_4+1	;
				;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
				;
soft_mapper_register	DSB 1	; Used to store a copy of the last thing written to MAPPER_REGISTER
				;
ENDE				;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
ENUM $0100			;
				;
ENDE				;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
ENUM $0200			;
				;
oam		DSB 256		;
				;
ENDE				;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
ENUM $0300			;
				;
ENDE				;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
ENUM $0400			;
				;
ENDE				;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
ENUM $0500			;
				;
ENDE				;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
ENUM $0600			;
				;
ENDE				;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
ENUM $0700			;
				;
ENDE				;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;